# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_cancel_order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_cancel_order.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1arequest_cancel_order.proto\x12\x03rti\"\xf7\x01\n\x12RequestCancelOrder\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x14\n\naccount_id\x18\x98\xb3\t \x01(\t\x12\x13\n\tbasket_id\x18\xdc\xdd\x06 \x01(\t\x12@\n\x0emanual_or_auto\x18\xd6\xb8\t \x01(\x0e\x32&.rti.RequestCancelOrder.OrderPlacement\"&\n\x0eOrderPlacement\x12\n\n\x06MANUAL\x10\x01\x12\x08\n\x04\x41UTO\x10\x02')
)



_REQUESTCANCELORDER_ORDERPLACEMENT = _descriptor.EnumDescriptor(
  name='OrderPlacement',
  full_name='rti.RequestCancelOrder.OrderPlacement',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MANUAL', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=245,
  serialized_end=283,
)
_sym_db.RegisterEnumDescriptor(_REQUESTCANCELORDER_ORDERPLACEMENT)


_REQUESTCANCELORDER = _descriptor.Descriptor(
  name='RequestCancelOrder',
  full_name='rti.RequestCancelOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestCancelOrder.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestCancelOrder.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fcm_id', full_name='rti.RequestCancelOrder.fcm_id', index=2,
      number=154013, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ib_id', full_name='rti.RequestCancelOrder.ib_id', index=3,
      number=154014, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='rti.RequestCancelOrder.account_id', index=4,
      number=154008, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='basket_id', full_name='rti.RequestCancelOrder.basket_id', index=5,
      number=110300, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manual_or_auto', full_name='rti.RequestCancelOrder.manual_or_auto', index=6,
      number=154710, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTCANCELORDER_ORDERPLACEMENT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=283,
)

_REQUESTCANCELORDER.fields_by_name['manual_or_auto'].enum_type = _REQUESTCANCELORDER_ORDERPLACEMENT
_REQUESTCANCELORDER_ORDERPLACEMENT.containing_type = _REQUESTCANCELORDER
DESCRIPTOR.message_types_by_name['RequestCancelOrder'] = _REQUESTCANCELORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestCancelOrder = _reflection.GeneratedProtocolMessageType('RequestCancelOrder', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTCANCELORDER,
  __module__ = 'request_cancel_order_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestCancelOrder)
  ))
_sym_db.RegisterMessage(RequestCancelOrder)


# @@protoc_insertion_point(module_scope)
