# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_show_order_history_detail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_show_order_history_detail.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\'request_show_order_history_detail.proto\x12\x03rti\"\xa8\x01\n\x1dRequestShowOrderHistoryDetail\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x14\n\naccount_id\x18\x98\xb3\t \x01(\t\x12\x13\n\tbasket_id\x18\xdc\xdd\x06 \x01(\t\x12\x0e\n\x04\x64\x61te\x18\x97\xe0\x06 \x01(\t')
)




_REQUESTSHOWORDERHISTORYDETAIL = _descriptor.Descriptor(
  name='RequestShowOrderHistoryDetail',
  full_name='rti.RequestShowOrderHistoryDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestShowOrderHistoryDetail.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestShowOrderHistoryDetail.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fcm_id', full_name='rti.RequestShowOrderHistoryDetail.fcm_id', index=2,
      number=154013, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ib_id', full_name='rti.RequestShowOrderHistoryDetail.ib_id', index=3,
      number=154014, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='rti.RequestShowOrderHistoryDetail.account_id', index=4,
      number=154008, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='basket_id', full_name='rti.RequestShowOrderHistoryDetail.basket_id', index=5,
      number=110300, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='rti.RequestShowOrderHistoryDetail.date', index=6,
      number=110615, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=217,
)

DESCRIPTOR.message_types_by_name['RequestShowOrderHistoryDetail'] = _REQUESTSHOWORDERHISTORYDETAIL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestShowOrderHistoryDetail = _reflection.GeneratedProtocolMessageType('RequestShowOrderHistoryDetail', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTSHOWORDERHISTORYDETAIL,
  __module__ = 'request_show_order_history_detail_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestShowOrderHistoryDetail)
  ))
_sym_db.RegisterMessage(RequestShowOrderHistoryDetail)


# @@protoc_insertion_point(module_scope)
