# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_tick_bar_replay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_tick_bar_replay.proto',
  package='rti',
  serialized_pb=_b('\n\x1drequest_tick_bar_replay.proto\x12\x03rti\"\xc1\x05\n\x14RequestTickBarReplay\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06symbol\x18\x94\xdc\x06 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x35\n\x08\x62\x61r_type\x18\xa0\xa3\x07 \x01(\x0e\x32!.rti.RequestTickBarReplay.BarType\x12<\n\x0c\x62\x61r_sub_type\x18\xa8\xa3\x07 \x01(\x0e\x32$.rti.RequestTickBarReplay.BarSubType\x12\x1c\n\x12\x62\x61r_type_specifier\x18\xc2\x85\t \x01(\t\x12\x15\n\x0bstart_index\x18\xaa\xab\t \x01(\x05\x12\x16\n\x0c\x66inish_index\x18\xab\xab\t \x01(\x05\x12\x18\n\x0euser_max_count\x18\xa4\xb3\t \x01(\x05\x12!\n\x17\x63ustom_session_open_ssm\x18\xa9\xa3\x07 \x01(\x05\x12\"\n\x18\x63ustom_session_close_ssm\x18\xaa\xa3\x07 \x01(\x05\x12\x38\n\tdirection\x18\x85\x8e\t \x01(\x0e\x32#.rti.RequestTickBarReplay.Direction\x12\x39\n\ntime_order\x18\xbb\x8e\t \x01(\x0e\x32#.rti.RequestTickBarReplay.TimeOrder\x12\x15\n\x0bresume_bars\x18\xaa\xb0\t \x01(\x08\"6\n\x07\x42\x61rType\x12\x0c\n\x08TICK_BAR\x10\x01\x12\r\n\tRANGE_BAR\x10\x02\x12\x0e\n\nVOLUME_BAR\x10\x03\"%\n\nBarSubType\x12\x0b\n\x07REGULAR\x10\x01\x12\n\n\x06\x43USTOM\x10\x02\" \n\tDirection\x12\t\n\x05\x46IRST\x10\x01\x12\x08\n\x04LAST\x10\x02\"(\n\tTimeOrder\x12\x0c\n\x08\x46ORWARDS\x10\x01\x12\r\n\tBACKWARDS\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUESTTICKBARREPLAY_BARTYPE = _descriptor.EnumDescriptor(
  name='BarType',
  full_name='rti.RequestTickBarReplay.BarType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TICK_BAR', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANGE_BAR', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOLUME_BAR', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=575,
  serialized_end=629,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTICKBARREPLAY_BARTYPE)

_REQUESTTICKBARREPLAY_BARSUBTYPE = _descriptor.EnumDescriptor(
  name='BarSubType',
  full_name='rti.RequestTickBarReplay.BarSubType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGULAR', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=631,
  serialized_end=668,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTICKBARREPLAY_BARSUBTYPE)

_REQUESTTICKBARREPLAY_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='rti.RequestTickBarReplay.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIRST', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAST', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=670,
  serialized_end=702,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTICKBARREPLAY_DIRECTION)

_REQUESTTICKBARREPLAY_TIMEORDER = _descriptor.EnumDescriptor(
  name='TimeOrder',
  full_name='rti.RequestTickBarReplay.TimeOrder',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FORWARDS', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKWARDS', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=704,
  serialized_end=744,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTICKBARREPLAY_TIMEORDER)


_REQUESTTICKBARREPLAY = _descriptor.Descriptor(
  name='RequestTickBarReplay',
  full_name='rti.RequestTickBarReplay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestTickBarReplay.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestTickBarReplay.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='rti.RequestTickBarReplay.symbol', index=2,
      number=110100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.RequestTickBarReplay.exchange', index=3,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bar_type', full_name='rti.RequestTickBarReplay.bar_type', index=4,
      number=119200, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bar_sub_type', full_name='rti.RequestTickBarReplay.bar_sub_type', index=5,
      number=119208, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bar_type_specifier', full_name='rti.RequestTickBarReplay.bar_type_specifier', index=6,
      number=148162, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_index', full_name='rti.RequestTickBarReplay.start_index', index=7,
      number=153002, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finish_index', full_name='rti.RequestTickBarReplay.finish_index', index=8,
      number=153003, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_max_count', full_name='rti.RequestTickBarReplay.user_max_count', index=9,
      number=154020, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_session_open_ssm', full_name='rti.RequestTickBarReplay.custom_session_open_ssm', index=10,
      number=119209, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_session_close_ssm', full_name='rti.RequestTickBarReplay.custom_session_close_ssm', index=11,
      number=119210, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='rti.RequestTickBarReplay.direction', index=12,
      number=149253, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_order', full_name='rti.RequestTickBarReplay.time_order', index=13,
      number=149307, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resume_bars', full_name='rti.RequestTickBarReplay.resume_bars', index=14,
      number=153642, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTTICKBARREPLAY_BARTYPE,
    _REQUESTTICKBARREPLAY_BARSUBTYPE,
    _REQUESTTICKBARREPLAY_DIRECTION,
    _REQUESTTICKBARREPLAY_TIMEORDER,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=744,
)

_REQUESTTICKBARREPLAY.fields_by_name['bar_type'].enum_type = _REQUESTTICKBARREPLAY_BARTYPE
_REQUESTTICKBARREPLAY.fields_by_name['bar_sub_type'].enum_type = _REQUESTTICKBARREPLAY_BARSUBTYPE
_REQUESTTICKBARREPLAY.fields_by_name['direction'].enum_type = _REQUESTTICKBARREPLAY_DIRECTION
_REQUESTTICKBARREPLAY.fields_by_name['time_order'].enum_type = _REQUESTTICKBARREPLAY_TIMEORDER
_REQUESTTICKBARREPLAY_BARTYPE.containing_type = _REQUESTTICKBARREPLAY
_REQUESTTICKBARREPLAY_BARSUBTYPE.containing_type = _REQUESTTICKBARREPLAY
_REQUESTTICKBARREPLAY_DIRECTION.containing_type = _REQUESTTICKBARREPLAY
_REQUESTTICKBARREPLAY_TIMEORDER.containing_type = _REQUESTTICKBARREPLAY
DESCRIPTOR.message_types_by_name['RequestTickBarReplay'] = _REQUESTTICKBARREPLAY

RequestTickBarReplay = _reflection.GeneratedProtocolMessageType('RequestTickBarReplay', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTTICKBARREPLAY,
  __module__ = 'request_tick_bar_replay_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestTickBarReplay)
  ))
_sym_db.RegisterMessage(RequestTickBarReplay)


# @@protoc_insertion_point(module_scope)
