# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_account_list.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_account_list.proto',
  package='rti',
  serialized_pb=_b('\n\x1arequest_account_list.proto\x12\x03rti\"\xe0\x01\n\x12RequestAccountList\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x35\n\tuser_type\x18\xb4\xb3\t \x01(\x0e\x32 .rti.RequestAccountList.UserType\"E\n\x08UserType\x12\x11\n\rUSER_TYPE_FCM\x10\x01\x12\x10\n\x0cUSER_TYPE_IB\x10\x02\x12\x14\n\x10USER_TYPE_TRADER\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUESTACCOUNTLIST_USERTYPE = _descriptor.EnumDescriptor(
  name='UserType',
  full_name='rti.RequestAccountList.UserType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_FCM', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_IB', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_TRADER', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=191,
  serialized_end=260,
)
_sym_db.RegisterEnumDescriptor(_REQUESTACCOUNTLIST_USERTYPE)


_REQUESTACCOUNTLIST = _descriptor.Descriptor(
  name='RequestAccountList',
  full_name='rti.RequestAccountList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestAccountList.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestAccountList.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fcm_id', full_name='rti.RequestAccountList.fcm_id', index=2,
      number=154013, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ib_id', full_name='rti.RequestAccountList.ib_id', index=3,
      number=154014, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_type', full_name='rti.RequestAccountList.user_type', index=4,
      number=154036, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTACCOUNTLIST_USERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=260,
)

_REQUESTACCOUNTLIST.fields_by_name['user_type'].enum_type = _REQUESTACCOUNTLIST_USERTYPE
_REQUESTACCOUNTLIST_USERTYPE.containing_type = _REQUESTACCOUNTLIST
DESCRIPTOR.message_types_by_name['RequestAccountList'] = _REQUESTACCOUNTLIST

RequestAccountList = _reflection.GeneratedProtocolMessageType('RequestAccountList', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTACCOUNTLIST,
  __module__ = 'request_account_list_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestAccountList)
  ))
_sym_db.RegisterMessage(RequestAccountList)


# @@protoc_insertion_point(module_scope)
