# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_front_month_contract.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='response_front_month_contract.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n#response_front_month_contract.proto\x12\x03rti\"\xee\x01\n\x1aResponseFrontMonthContract\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x11\n\x07rp_code\x18\x9e\x8d\x08 \x03(\t\x12\x10\n\x06symbol\x18\x94\xdc\x06 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x1f\n\x15is_front_month_symbol\x18\xae\x8d\t \x01(\x08\x12\x15\n\x0bsymbol_name\x18\xa3\x8d\x06 \x01(\t\x12\x18\n\x0etrading_symbol\x18\xa7\xcb\t \x01(\t\x12\x1a\n\x10trading_exchange\x18\xa8\xcb\t \x01(\t')
)




_RESPONSEFRONTMONTHCONTRACT = _descriptor.Descriptor(
  name='ResponseFrontMonthContract',
  full_name='rti.ResponseFrontMonthContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.ResponseFrontMonthContract.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.ResponseFrontMonthContract.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rp_code', full_name='rti.ResponseFrontMonthContract.rp_code', index=2,
      number=132766, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='rti.ResponseFrontMonthContract.symbol', index=3,
      number=110100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.ResponseFrontMonthContract.exchange', index=4,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_front_month_symbol', full_name='rti.ResponseFrontMonthContract.is_front_month_symbol', index=5,
      number=149166, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol_name', full_name='rti.ResponseFrontMonthContract.symbol_name', index=6,
      number=100003, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trading_symbol', full_name='rti.ResponseFrontMonthContract.trading_symbol', index=7,
      number=157095, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trading_exchange', full_name='rti.ResponseFrontMonthContract.trading_exchange', index=8,
      number=157096, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=283,
)

DESCRIPTOR.message_types_by_name['ResponseFrontMonthContract'] = _RESPONSEFRONTMONTHCONTRACT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseFrontMonthContract = _reflection.GeneratedProtocolMessageType('ResponseFrontMonthContract', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEFRONTMONTHCONTRACT,
  __module__ = 'response_front_month_contract_pb2'
  # @@protoc_insertion_point(class_scope:rti.ResponseFrontMonthContract)
  ))
_sym_db.RegisterMessage(ResponseFrontMonthContract)


# @@protoc_insertion_point(module_scope)
